export const FETCH_TREND = "FETCH__TREND";
export const FETCH_TREND_SUCCESS = "FETCH_TREND_SUCCESS";
export const FETCH_TREND_ERROR = "FETCH_TREND_ERROR";
export const FETCH_POPULAR_PRODUCT_SUCCESS = "FETCH_POPULAR_PRODUCT_SUCCESS";
export const FETCH_POPULAR_PRODUCT_ERROR = "FETCH_POPULAR_PRODUCT_ERROR";
export const FETCH_PRODUCT_MEN_HOME = "FETCH_PRODUCT_MEN_HOME";
export const FETCH_PRODUCT_WOMEN_HOME = "FETCH_PRODUCT_WOMEN_HOME";
export const FETCH_PRODUCT_HOME_ERROR = "FETCH_PRODUCT_HOME_ERROR";
export const FETCH_SHOW_IMG = "FETCH_SHOW_IMG";
export const FETCH_SHOW_IMG_SUCCESS = "FETCH_SHOW_IMG_SUCCESS";
export const FETCH_SHOW_IMG_ERROR = "FETCH_SHOW_IMG_ERROR";
export const FETCH_SLIDE_IMG = "FETCH_SLIDE_IMG";
export const FETCH_SLIDE_IMG_SUCCESS = "FETCH_SLIDE_IMG_SUCCESS";
export const FETCH_SLIDE_IMG_ERROR = "FETCH_SLIDE_IMG_ERROR";
export const FETCH_PRODUCT_MAN_SUCCESS = "FETCH_PRODUCT_MAN_SUCCESS";
export const FETCH_PRODUCT_MAN_ERROR = "FETCH_PRODUCT_MAN_ERROR";
export const FETCH_PRODUCT_WOMEN = "FETCH_PRODUCT_WOMEN";
export const FETCH_PRODUCT_WOMEN_SUCCESS = "FETCH_PRODUCT_WOMEN_SUCCESS";
export const FETCH_PRODUCT_WOMEN_ERROR = "FETCH_PRODUCT_WOMEN_ERROR";
export const GET_PRODUCT_ID = "GET_PRODUCT_ID";
export const FETCH_PRODUCT_DETAIL = "FETCH_PRODUCT_DETAIL";
export const FETCH_PRODUCT_DETAIL_SUCCESS = "FETCH_PRODUCT_DETAIL_SUCCESS";
export const FETCH_PRODUCT_DETAIL_ERROR = "FETCH_PRODUCT_DETAIL_ERROR";
export const FETCH_PRODUCT_DETAIL_VIEW_MORE_SUCCESS = "FETCH_PRODUCT_DETAIL_VIEW_MORE_SUCCESS";
export const FETCH_PRODUCT_DETAIL_VIEW_MORE_SUCCESS_WOMEN = "FETCH_PRODUCT_DETAIL_VIEW_MORE_SUCCESS_WOMEN";
export const FETCH_PRODUCT_DETAIL_VIEW_MORE_ERROR = "FETCH_PRODUCT_DETAIL_VIEW_MORE_ERROR";

export const OPEN_CART = "OPEN_CART";
export const CLOSE_CART = "CLOSE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";
export const GET_CART_PRODUCT = "GET_CART_PRODUCT";
export const GET_CART_PRODUCT_SUCCESS = "GET_CART_PRODUCT_SUCCESS";
export const GET_CART_PRODUCT_ERROR = "GET_CART_PRODUCT_ERROR";
export const INCREASE_CART_PRODUCT = "INCREASE_CART_PRODUCT";
export const INCREASE_CART_PRODUCT_SUCCESS = "INCREASE_CART_PRODUCT_SUCCESS";
export const INCREASE_CART_PRODUCT_ERROR = "INCREASE_CART_PRODUCT_ERROR";
export const REDUCTION_CART_PRODUCT = "REDUCTION_CART_PRODUCT";
export const REDUCTION_CART_PRODUCT_SUCCESS = "REDUCTION_CART_PRODUCT_SUCCESS";
export const REDUCTION_CART_PRODUCT_ERROR = "REDUCTION_CART_PRODUCT_ERROR";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const OPEN_SIGN_IN = "OPEN_SIGN_IN";
export const CLOSE_SIGN_IN = "OPEN_SIGN_IN";
export const IS_SIGN_IN = "IS_SIGN_IN";

export const LOGN_OUT = "LOGN_OUT";

export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

export const GET_BOOKING = "GET_BOOKING";
export const GET_BOOKING_SUCCESS = "GET_BOOKING_SUCCESS";
export const GET_BOOKING_ERROR = "GET_BOOKING_ERROR";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const BOOKING_PRODUCTS = "BOOKING_PRODUCTS";
export const BOOKING_PRODUCTS_SUCCESS = "BOOKING_PRODUCTS_SUCCESS";
export const BOOKING_PRODUCTS_ERROR = "BOOKING_PRODUCTS_ERROR";
export const TEST = "TEST";